### PR TITLE
Private Events

### PR DESCRIPTION
**Pull request by abmAsadullah**
### Created private event rails app
* People can join
* Can create event
* Can attend an event

### CODE REVIEW

**Review by ElijahTobs — CHANGES_REQUESTED** [review]
# Status: Changes Required :recycle: 

## Hi @abmAsadullah :wave: 

You've done well so far :+1:  and I commend you for that :clap: 
However, there are still some changes to be made before this project can be approved.

## REQUIRED

* [x] Please, make all the changes as requested by the previous TSE.
* [x] You're expected to have a descriptive README file - feel free to use [this template](https://github.com/microverseinc/readme-template)
* [x] Fix the linter error
* [x] In the events show page, correct the typo **"Arrenged by"** to **"Arranged by"**
image
* [x] In your events controller, your **create** action should use the #build method on association, i.e. `current_user.events.build(event_params)` ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/associations/build_method_requirement.png) from [Odin](https://www.theodinproject.com/courses/ruby-on-rails/lessons/associations))
* [x] In your users controller, the show action is supposed to show events created by user, i.e. `@created_events = current_user.events` ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/associations/current_user_show_requirement.png) from [Odin](https://www.theodinproject.com/courses/ruby-on-rails/lessons/associations))

#### Tests

* [x] models have unit tests for validations and associations (Rspec) ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/associations/unit_tests_requirement.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/49723079/))
* [x] authentication has integration tests (Rspec + Capybara) ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/associations/integration_tests_requirement.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/49723079/))
* [x] event managment features have integration tests (Rspec + Capybara) ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/associations/integration_tests_requirement.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/49723079/))


### Make the requested changes and submit for another review.
## Happy Coding :computer: 

_Feel free to reach out to me on slack_ **`@Elijah Ayandokun`**
  **Elijah O. Ayandokun**
[Github](https://github.com/ElijahTobs) | [LinkedIn](https://www.linkedin.com/in/ayandokunelijah/) | [Twitter](https://twitter.com/ElijahTobs)

**Review by ebeagusamuel — CHANGES_REQUESTED** [review]
# Changes Requested #:recycle: 
### Hey there :wave: 
##### Well done on the job done so far on this project. You are almost there and just a few more changes to get the project approved.
- [x] In your users controller, the show action is supposed to show events created bycurent_user, i.e. @created_events = current_user.events (screenshot from Odin).
- [x] authentication has integration tests (Rspec + Capybara) (screenshot from Pathwright). You should have done a manual authentication yourself as opposed to using device gem. That way you would be able to test out the feature. Please create a manual authentication feature that you can be able to test.
#### Request another review when you are done making the changes.
slack(@ebeagusamuel)

**Review by andresporras3423 — CHANGES_REQUESTED** [review]
### Status: Changes Required :recycle:
**Hello Asad Asadullah** 
Good job with the improvements for this project :muscle:  :muscle:
Your project meets most of the requirements :clap: :clap: :clap:  
Just a couple of details to improve before you can go ahead:

- [x] Fix Rubocop offenses
- [x] Add a screenshot to the README file
 
Please request another review once you are ready! :+1: 
 
Happy coding :relaxed:
 
Oscar Andrés Russi Porras

**Review by cristianCeamatu — APPROVED** [review]
### 🥇 APPROVED 🥇 Congratulations and good luck with the next projects!

If you ever need any help or notice that you are wasting too many hours on a bug don't hesitate to contact me on Slack.

Best regards,
Cristian Ceamatu
Slack: Cristian Viorel Ceamatu

**Pull request merged**
